version: "3.0"

services:
  api:
    container_name: "api"
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_DEFAULT_REGION=dummy
      - AWS_SECRET_ACCESS_KEY=ap-northeast-1